INSERT INTO user_details (id,birth_date,name) VALUES (10000, current_date(),'Guts');
insert into user_details (id, birth_date, name) values (1, '2022-08-29', 'Fulvia');
insert into user_details (id, birth_date, name) values (2, '2022-05-18', 'Gaspar');
insert into user_details (id, birth_date, name) values (3, '2024-03-13', 'Keane');
insert into user_details (id, birth_date, name) values (4, '2022-05-01', 'Mattie');
insert into user_details (id, birth_date, name) values (5, '2024-02-10', 'Siana');
insert into user_details (id, birth_date, name) values (6, '2023-05-14', 'Alina');
insert into user_details (id, birth_date, name) values (7, '2023-08-13', 'Silvester');
insert into user_details (id, birth_date, name) values (8, '2024-05-03', 'Hattie');
insert into user_details (id, birth_date, name) values (9, '2022-07-21', 'Florentia');
insert into user_details (id, birth_date, name) values (10, '2022-11-28', 'Beitris');
insert into post (id, description,user_id) values (10000, 'Griffith!!!', 10000);
insert into post (id, description, user_id) values (12, 'Unspecified B-cell lymphoma, unspecified site', 1);
insert into post (id, description, user_id) values (132, 'Unspecified B-cell lymphom', 1);
insert into post (id, description, user_id) values (22, 'Path fx in oth disease, unsp site, subs for fx w routn heal', 2);
insert into post (id, description, user_id) values (32, 'Inj muscle, fascia and tendon of unsp hip, subs encntr', 3);
insert into post (id, description, user_id) values (42, 'Contact with hot engines, machinery and tools, sequela', 4);
insert into post (id, description, user_id) values (52, 'Carbuncle of perineum', 5);
insert into post (id, description, user_id) values (62, 'Osteonecrosis due to previous trauma, unspecified ankle', 6);
insert into post (id, description, user_id) values (72, 'Primary blast injury of fallopian tube, unsp, init encntr', 7);
insert into post (id, description, user_id) values (82, 'Hemiplga fol oth cerebvasc disease aff right nondom side', 8);
insert into post (id, description, user_id) values (92, 'Unstbl burst fx first thor vert, subs for fx w routn heal', 9);
insert into post (id, description, user_id) values (102, 'Acute lymphangitis of right lower limb', 10);
